#!/usr/bin/env ruby
QUOTES = [
  "Once you have their money, you never give it back.",
  "The best deal is the one that makes the most profit.",
  "Never spend more for an acquisition than you have to.",
  "A woman wearing clothes is like a man in the kitchen.",
  "Always exaggerate your estimates.",
  "Never allow family to stand in the way of opportunity.",
  "Always keep your ears open.",
  "Small print leads to large risk.",
  "Opportunity, plus instinct, equals profit.",
  "Greed is eternal.",
  "Even if it's free, you can always buy it cheaper.",
  "Anything worth selling is worth selling twice.",
  "Anything worth doing is worth doing for money.",
  "Sometimes the quickest way to find profits is to let them find you.",
  "Dead men close no deals.",
  "A deal is a deal (is a deal)...until a better one comes along.",
  "A contract is a contract is a contract... but only between Ferengi.",
  "A Ferengi without profit is no Ferengi at all.",
  "Satisfaction is not guaranteed.",
  "He who dives under the table today lives to profit tomorrow.",
  "Never place friendship before profit.",
  "Wise men can hear profit in the wind.",
  "Nothing is more important than your health...except for your money.",
  "There's nothing more dangerous than an honest businessman.",
  "What's in it for me?",
  "Confidentiality equals profit.",
  "Never make fun of a Ferengi's mother.",
  "Insult something he cares about.",
  "It never hurts to suck up to the boss.",
  "War is good for business.",
  "Peace is good for business.",
  "The early investor reaps the most interest.",
  "Don't tell customers more than they need to know.",
  "She can touch your lobes but never your latinum.",
  "Profit is its own reward.",
  "Feed your greed, but not enough to choke it.",
  "Never confuse wisdom with luck.",
  "Expand or die.*",
  "Never trust a man wearing a better suit than your own.",
  "The bigger the smile, the sharper the knife.",
  "Never ask when you can take.",
  "Never trust anybody taller than you.",
  "Rate divided by time equals profit.",
  "Take joy from profit, and profit from joy.",
  "Good customers are as rare as latinum. Treasure them.",
  "There is no substitute for success.",
  "Free advice is seldom cheap.",
  "Keep your lies consistent.",
  "The riskier the road, the greater the profit.",
  "Work is the best therapy-at least for your employees.",
  "Win or lose, there's always Hupyrian beetle snuff.",
  "Someone's always got bigger ears.",
  "Ferengi are not responsible for the stupidity of other races.",
  "Knowledge equals profit.",
  "Home is where the heart is, but the stars are made of latinum.",
  "Every once in a while, declare peace. It confuses the Hell out of your enemies.",
  "If you break it, I'll charge you for it!",
  "Beware of the Vulcan greed for knowledge.",
  "The flimsier the product, the higher the price.",
  "Never let the competition know what you're thinking.",
  "Learn the customer's weaknesses, so that you can better take advantage of him.",
  "It ain't over 'til its over.",
  "Ask not what you can do for your profits, but what your profits can do for you.",
  "There are many paths to profit.",
  "Females and finances don't mix.",
  "Expand or die.*",
  "Enough is never enough.",
  "Every man has his price.",
  "Trust is the biggest liability of all.",
  "When it's good for business, tell the truth.",
  "Nature decays, but latinum lasts forever.",
  "Sleep can interfere with...",
  "Faith moves mountains...of inventory.",
  "There is no honor in poverty.",
  "Dignity and an empty sack is worth the sack.",
  "Exploitation begins at home.",
  "Treat people in your debt like family... exploit them.",
  "Never have sex with the boss' sister.",
  "Always have sex with the boss.",
  "Everything is for sale - even friendship.",
  "Even a blind man can recognize the glow of Latinum.",
  "You can't make a deal if you're dead.",
  "Listen to secrets, but never repeat them.",
  "Wives serve; brothers inherit.",
  "Only fools pay retail.",
  "There's nothing wrong with charity... as long as it winds up in your pocket.",
  "People love the bartender.",
  "Sell the sizzle, not the steak.",
  "Even in the worst of times, someone turns a profit.",
  "Whisper your way to success.",
  "Know your enemies... but do business with them always.",
  "Not even dishonesty can tarnish the shine of profit.",
  "When life hands you ungaberries, make detergent.",
  "A Ferengi waits to bid until his opponents have exhausted themselves.",
  "Not even dishonesty can tarnish the shine of profit.",
  "Let others keep their reputation. You keep their money.",
  "Hear all, trust nothing.",
  "Never cheat a Klingon... unless you're sure you can get away with it.",
  "Trouble comes in threes.",
  "It's always good business to know about new customers before they walk in your door.",
  "Location, location, location.",
  "A Ferengi chooses no side but his own",
  "The justification for profit is profit.",
  "New customers are like razor-toothed gree worms. They can be succulent, but sometimes they bite back.",
  "Sometimes, the only thing more dangerous than a question is an answer.",
  "Employees are the rungs on the ladder of success, don't hesitate to step on them.",
  "A good lie is easier to believe than the truth.",
  "Never begin a business transaction on an empty stomach.",
  "Never gamble with a telepath.",
  "You can't free a fish from water.",
  "Always know what you're buying.",
  "Sometimes what you get free cost entirely too much.",
  "Possession is eleven-tenths of the law!",
  "Beware the man who doesn't take time for Oo-mox.",
  "If that's what's written, then that's what's written.",
  "Latinum lasts longer than lust.",
  "Duck; death is tall.",
  "You can't buy fate.",
  "Never be afraid to mislabel a product.",
  "Time, like latinum, is a highly limited commodity.",
  "More is good...all is better.",
  "Always leave yourself an out.",
  "A wife is [a] luxury... a smart accountant a neccessity.",
  "When the messenger comes to appropriate your profits, kill the messenger.",
  "A wealthy man can afford everything except a conscience.",
  "Never let doubt interfere with your lust for Latinum.",
  "When in doubt, lie.",
  "Always inspect the merchandise before making a deal.",
  "If it ain't broke, don't fix it.",
  "Deep down, everyone's a Ferengi.",
  "No good deed ever goes unpunished.",
  "Always get somebody else to do the lifting.",
  "Never get into anything that you can't get out of.",
  "A man is only worth the sum of his possessions.",
  "An angry man is an enemy, and a satisfied man is an ally..",
  "The less employees know about the cash flow, the smaller the share they can demand.",
  "Only a fool passes up a business opportunity.",
  "The more time they take deciding, the more money they will spend.",
]

puts QUOTES.shuffle.first
