 set nocompatible               " be iMproved
  filetype off                   " required!
set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

"let vundle manage vundle
Bundle 'gmarik/vundle'

"Tab completion
" Bundle 'ervandew/supertab'
"Buff Explorer
Bundle 'bufexplorer.zip'
"Leader-sd Trim WhiteSpace
Bundle 'trailing-whitespace'
"Powerline-Vim
Bundle 'Lokaltog/vim-powerline'
"Up and Down - Bubble Lines
Bundle 'vim-scripts/upAndDown'

syntax enable
set background=dark
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set number
set hidden
set noswapfile
set incsearch " Find the next match as we type the search
set hlsearch " Highlight searches by default
set scrolloff=8 "Set point where the file scrolls
set ignorecase
set nowrap


let mapleader = ","

"Fix cursor for column select
if exists('$TMUX')
  let &t_SI = "\<Esc>[3 q"
  let &t_EI = "\<Esc>[0 q"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
" Disable scrolling with the mouse
map <ScrollWheelUp> <Nop>
map <ScrollWheelDown> <Nop>
map <ScrollWheelLeft> <Nop>
map <ScrollWheelRight> <Nop>

map <Leader>, <C-^>

" Trim & save
noremap <Leader>sd :FixWhitespace<CR>:w<CR>
" Select all
map <Leader>a ggVG

" Movement & wrapped long lines
" This solves the problem that pressing down jumps your cursor 'over' the current line to the next line
nnoremap j gj
nnoremap k gk

" Easy window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Reselect visual block after indent
vnoremap < <gv
vnoremap > >gv

" Highlight word at cursor without changing position
nnoremap <Leader>h *<C-O>

" Jump to start and end of line using the home row keys
noremap H ^
noremap L $

" Clear search
noremap <silent><Leader>/ :nohls<CR>

" Yank and put system pasteboard with <Leader>y/p
noremap <Leader>y "*y
nnoremap <Leader>yy "*yy
noremap <Leader>p "*p
noremap <Leader>P "*P


"Highlight the current line you are on.
hi CursorLineNr term=bold ctermfg=225 ctermbg=88 guifg=#ccc5c4
set cursorline

"Highlighting on table completion
"hi Pmenu ctermbg=232 ctermfg=255 gui=bold


hi Search cterm=underline ctermfg=201

"Powerline Settings

set nocompatible   " Disable vi-compatibility
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs



" Persistent Undo
set undodir=$HOME/.vim/undodir
set undofile
set undolevels=1000
set undoreload=10000

" Fold settings
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=99
set foldminlines=0

" Space to toggle folds
nnoremap <Space> za
vnoremap <Space> za
