alias v="vim"
alias work="cd ~/work"
alias envision="cd ~/work/envision"
alias whatalias=" alias | grep"
alias xx="exit"
alias zshrc="vim ~/.dotfiles/config/zshrc"
alias dotfiles="~/.dotfiles/"
alias gshw="git show"
alias gsw="git show"
alias editalias='vim ~/.dotfiles/config/aliases.sh'
alias vimkeys='~/.dotfiles/vim/keybindings'
alias killrspec='pkill "rbenv.*rspec"'
